# Generated by Django 5.0.3 on 2024-04-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image2',
            field=models.ImageField(null=True, upload_to='images2'),
        ),
    ]
